# Generated by Django 4.0.3 on 2022-03-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums_api', '0002_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
    ]
