# Generated by Django 4.0.3 on 2022-03-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums_api', '0003_remove_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
