# Generated by Django 4.0.3 on 2022-03-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums_api', '0004_album_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.TextField(default='untitled album')),
            ],
        ),
    ]
