# Generated by Django 4.0.3 on 2022-03-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists_api', '0003_alter_artist_albums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='albums',
        ),
    ]
