# Generated by Django 4.0.3 on 2022-03-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists_api', '0005_remove_artist_soloartists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='language',
            new_name='image',
        ),
    ]
