# Generated by Django 4.0.3 on 2022-03-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists_api', '0006_rename_language_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
