# Generated by Django 4.0.3 on 2022-03-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists_api', '0007_alter_artist_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.TextField(default='No artist entered')),
            ],
        ),
    ]
